#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/DRG

PRODUCT_COPY_FILES += \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Bluetooth_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/General_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Global_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Handset_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Hdmi_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Headset_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/Speaker_cal.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/DRG/sdm660-snd-card-drg/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/DRG/sdm660-snd-card-drg/workspaceFile.qwsp \
    vendor/nokia/DRG/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/DRG/proprietary/vendor/etc/audio_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/camera/calibration_test.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calibration_test.bin \
    vendor/nokia/DRG/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/camera/s5k3p9sx_drg_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p9sx_drg_front_chromatix.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/camera/s5k3p9sx_drg_main_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p9sx_drg_main_chromatix.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/camera/s5k5e9_drg_aux_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e9_drg_aux_chromatix.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/nokia/DRG/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/nokia/DRG/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/nokia/DRG/proprietary/vendor/etc/sensors/sensor_def_qcomdev_drg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev_drg.conf \
    vendor/nokia/DRG/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nokia/DRG/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/nokia/DRG/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/nokia/DRG/proprietary/vendor/etc/wifi/bdf/bdwlan_DRG_cal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_DRG_cal.bin \
    vendor/nokia/DRG/proprietary/vendor/etc/wifi/bdf/bdwlan_TAS_cal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_TAS_cal.bin \
    vendor/nokia/DRG/proprietary/vendor/etc/wifi/bdf/bdwlan_def.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_def.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/TAS2557MSSMono_DRG.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TAS2557MSSMono_DRG.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/TFA9894_drg.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9894_drg.cnt \
    vendor/nokia/DRG/proprietary/vendor/firmware/TFA9894_drg.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9894_drg.ini \
    vendor/nokia/DRG/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/nokia/DRG/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b00 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b02 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b03 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b04 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b05 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b06 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b00 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b02 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b03 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b04 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b05 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cmnlib64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b06 \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_config.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config.cfg \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_config_hlt.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_hlt.cfg \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_config_oflim.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_oflim.cfg \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_config_truly.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_truly.cfg \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_firmware_hlt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_hlt.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_firmware_oflim.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_oflim.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/goodix_firmware_truly.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_truly.bin \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b00 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b01 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b02 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b03 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b04 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b05 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b06 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.b07 \
    vendor/nokia/DRG/proprietary/vendor/firmware/gxfp3258_drg.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3258_drg.mdt \
    vendor/nokia/DRG/proprietary/vendor/usr/keylayout/goodix_fp.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/goodix_fp.kl

PRODUCT_PACKAGES += \
    libsensor1 \
    libsensor_reg \
    sensor_calibrate \
    sensors.ssc \
    camera.sdm660 \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_fp5510_drg_main \
    libadiertac \
    libadm \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libaoa \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_dualcam_refocus_DRG \
    libarcsoft_night_shot \
    libarcsoft_picselfie_algorithm \
    libarcsoft_smart_denoise \
    libaudcal \
    libaudioalsa \
    libchromatix_s5k3p9sx_drg_front_2nd_common \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_preview \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_front_2nd_cpp_video \
    libchromatix_s5k3p9sx_drg_front_2nd_default_preview_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_default_video \
    libchromatix_s5k3p9sx_drg_front_2nd_default_video_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_2nd_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_liveshot \
    libchromatix_s5k3p9sx_drg_front_2nd_postproc \
    libchromatix_s5k3p9sx_drg_front_2nd_preview \
    libchromatix_s5k3p9sx_drg_front_2nd_snapshot \
    libchromatix_s5k3p9sx_drg_front_2nd_versions \
    libchromatix_s5k3p9sx_drg_front_2nd_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_front_2nd_zsl_video_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_common \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_preview \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_front_3rd_cpp_video \
    libchromatix_s5k3p9sx_drg_front_3rd_default_preview_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_default_video \
    libchromatix_s5k3p9sx_drg_front_3rd_default_video_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_3rd_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_liveshot \
    libchromatix_s5k3p9sx_drg_front_3rd_postproc \
    libchromatix_s5k3p9sx_drg_front_3rd_preview \
    libchromatix_s5k3p9sx_drg_front_3rd_snapshot \
    libchromatix_s5k3p9sx_drg_front_3rd_versions \
    libchromatix_s5k3p9sx_drg_front_3rd_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_front_3rd_zsl_video_3a \
    libchromatix_s5k3p9sx_drg_front_4th_common \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_preview \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_front_4th_cpp_video \
    libchromatix_s5k3p9sx_drg_front_4th_default_preview_3a \
    libchromatix_s5k3p9sx_drg_front_4th_default_video \
    libchromatix_s5k3p9sx_drg_front_4th_default_video_3a \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_4th_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_front_4th_liveshot \
    libchromatix_s5k3p9sx_drg_front_4th_postproc \
    libchromatix_s5k3p9sx_drg_front_4th_preview \
    libchromatix_s5k3p9sx_drg_front_4th_snapshot \
    libchromatix_s5k3p9sx_drg_front_4th_versions \
    libchromatix_s5k3p9sx_drg_front_4th_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_front_4th_zsl_video_3a \
    libchromatix_s5k3p9sx_drg_front_common \
    libchromatix_s5k3p9sx_drg_front_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_front_cpp_preview \
    libchromatix_s5k3p9sx_drg_front_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_front_cpp_video \
    libchromatix_s5k3p9sx_drg_front_default_preview_3a \
    libchromatix_s5k3p9sx_drg_front_default_video \
    libchromatix_s5k3p9sx_drg_front_default_video_3a \
    libchromatix_s5k3p9sx_drg_front_hfr_120 \
    libchromatix_s5k3p9sx_drg_front_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_front_hfr_60 \
    libchromatix_s5k3p9sx_drg_front_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_front_hfr_90 \
    libchromatix_s5k3p9sx_drg_front_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_front_liveshot \
    libchromatix_s5k3p9sx_drg_front_postproc \
    libchromatix_s5k3p9sx_drg_front_preview \
    libchromatix_s5k3p9sx_drg_front_snapshot \
    libchromatix_s5k3p9sx_drg_front_versions \
    libchromatix_s5k3p9sx_drg_front_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_front_zsl_video_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_common \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_preview \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_main_2nd_cpp_video \
    libchromatix_s5k3p9sx_drg_main_2nd_default_preview_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_default_video \
    libchromatix_s5k3p9sx_drg_main_2nd_default_video_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_120 \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_60 \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_90 \
    libchromatix_s5k3p9sx_drg_main_2nd_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_liveshot \
    libchromatix_s5k3p9sx_drg_main_2nd_postproc \
    libchromatix_s5k3p9sx_drg_main_2nd_preview \
    libchromatix_s5k3p9sx_drg_main_2nd_preview_longexposure \
    libchromatix_s5k3p9sx_drg_main_2nd_snapshot \
    libchromatix_s5k3p9sx_drg_main_2nd_snapshot_longexposure \
    libchromatix_s5k3p9sx_drg_main_2nd_versions \
    libchromatix_s5k3p9sx_drg_main_2nd_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_zsl_preview_panorama_3a \
    libchromatix_s5k3p9sx_drg_main_2nd_zsl_video_3a \
    libchromatix_s5k3p9sx_drg_main_common \
    libchromatix_s5k3p9sx_drg_main_cpp_hfr_120 \
    libchromatix_s5k3p9sx_drg_main_cpp_hfr_60 \
    libchromatix_s5k3p9sx_drg_main_cpp_hfr_90 \
    libchromatix_s5k3p9sx_drg_main_cpp_liveshot \
    libchromatix_s5k3p9sx_drg_main_cpp_preview \
    libchromatix_s5k3p9sx_drg_main_cpp_snapshot \
    libchromatix_s5k3p9sx_drg_main_cpp_video \
    libchromatix_s5k3p9sx_drg_main_default_preview_3a \
    libchromatix_s5k3p9sx_drg_main_default_video \
    libchromatix_s5k3p9sx_drg_main_default_video_3a \
    libchromatix_s5k3p9sx_drg_main_hfr_120 \
    libchromatix_s5k3p9sx_drg_main_hfr_120_3a \
    libchromatix_s5k3p9sx_drg_main_hfr_60 \
    libchromatix_s5k3p9sx_drg_main_hfr_60_3a \
    libchromatix_s5k3p9sx_drg_main_hfr_90 \
    libchromatix_s5k3p9sx_drg_main_hfr_90_3a \
    libchromatix_s5k3p9sx_drg_main_liveshot \
    libchromatix_s5k3p9sx_drg_main_postproc \
    libchromatix_s5k3p9sx_drg_main_preview \
    libchromatix_s5k3p9sx_drg_main_preview_longexposure \
    libchromatix_s5k3p9sx_drg_main_snapshot \
    libchromatix_s5k3p9sx_drg_main_snapshot_longexposure \
    libchromatix_s5k3p9sx_drg_main_versions \
    libchromatix_s5k3p9sx_drg_main_zsl_preview_3a \
    libchromatix_s5k3p9sx_drg_main_zsl_preview_panorama_3a \
    libchromatix_s5k3p9sx_drg_main_zsl_video_3a \
    libchromatix_s5k5e9_drg_aux_2nd_4k_preview_3a \
    libchromatix_s5k5e9_drg_aux_2nd_4k_video_3a \
    libchromatix_s5k5e9_drg_aux_2nd_common \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_hfr_120 \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_hfr_60 \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_hfr_90 \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_liveshot \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_preview \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_snapshot \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_video \
    libchromatix_s5k5e9_drg_aux_2nd_cpp_video_4k \
    libchromatix_s5k5e9_drg_aux_2nd_default_preview_3a \
    libchromatix_s5k5e9_drg_aux_2nd_default_video \
    libchromatix_s5k5e9_drg_aux_2nd_default_video_3a \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_120 \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_120_3a \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_60 \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_60_3a \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_90 \
    libchromatix_s5k5e9_drg_aux_2nd_hfr_90_3a \
    libchromatix_s5k5e9_drg_aux_2nd_liveshot \
    libchromatix_s5k5e9_drg_aux_2nd_postproc \
    libchromatix_s5k5e9_drg_aux_2nd_preview \
    libchromatix_s5k5e9_drg_aux_2nd_snapshot \
    libchromatix_s5k5e9_drg_aux_2nd_versions \
    libchromatix_s5k5e9_drg_aux_2nd_video_4k \
    libchromatix_s5k5e9_drg_aux_2nd_zsl_preview_3a \
    libchromatix_s5k5e9_drg_aux_2nd_zsl_video_3a \
    libchromatix_s5k5e9_drg_aux_4k_preview_3a \
    libchromatix_s5k5e9_drg_aux_4k_video_3a \
    libchromatix_s5k5e9_drg_aux_common \
    libchromatix_s5k5e9_drg_aux_cpp_hfr_120 \
    libchromatix_s5k5e9_drg_aux_cpp_hfr_60 \
    libchromatix_s5k5e9_drg_aux_cpp_hfr_90 \
    libchromatix_s5k5e9_drg_aux_cpp_liveshot \
    libchromatix_s5k5e9_drg_aux_cpp_preview \
    libchromatix_s5k5e9_drg_aux_cpp_snapshot \
    libchromatix_s5k5e9_drg_aux_cpp_video \
    libchromatix_s5k5e9_drg_aux_cpp_video_4k \
    libchromatix_s5k5e9_drg_aux_default_preview_3a \
    libchromatix_s5k5e9_drg_aux_default_video \
    libchromatix_s5k5e9_drg_aux_default_video_3a \
    libchromatix_s5k5e9_drg_aux_hfr_120 \
    libchromatix_s5k5e9_drg_aux_hfr_120_3a \
    libchromatix_s5k5e9_drg_aux_hfr_60 \
    libchromatix_s5k5e9_drg_aux_hfr_60_3a \
    libchromatix_s5k5e9_drg_aux_hfr_90 \
    libchromatix_s5k5e9_drg_aux_hfr_90_3a \
    libchromatix_s5k5e9_drg_aux_liveshot \
    libchromatix_s5k5e9_drg_aux_postproc \
    libchromatix_s5k5e9_drg_aux_preview \
    libchromatix_s5k5e9_drg_aux_snapshot \
    libchromatix_s5k5e9_drg_aux_versions \
    libchromatix_s5k5e9_drg_aux_video_4k \
    libchromatix_s5k5e9_drg_aux_zsl_preview_3a \
    libchromatix_s5k5e9_drg_aux_zsl_video_3a \
    libdepthmapwrapper \
    libfih_camera_effect \
    libflash_dummy_flash \
    libflash_pmic \
    libhal_dbg \
    libimage_matting \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3p9sx_drg_front \
    libmmcamera_s5k3p9sx_drg_front_eeprom \
    libmmcamera_s5k3p9sx_drg_main \
    libmmcamera_s5k3p9sx_drg_main_eeprom \
    libmmcamera_s5k3p9sx_drg_main_hlt_eeprom \
    libmmcamera_s5k5e9_drg_aux \
    libmmcamera_s5k5e9_drg_aux_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    android.hardware.keymaster@3.0-impl-qti \
    fingerprint.gxfp3258_drg \
    libgf_ca_gxfp3258_drg \
    libgf_hal_gxfp3258_drg \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    libvendor.goodix.hardware.fingerprintextension@1.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_800h_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    TAS2557MSSMono_DRG.ftcfg \
    cnss-daemon \
    android.hardware.keymaster@3.0-service-qti \
    mm-qcamera-app \
    sensors.qti
